import { FadeIn } from "@/components/shared/FadeIn";
import { 
  MessageSquare, 
  Heart, 
  Globe, 
  Clock, 
  CheckCircle2, 
  Image as ImageIcon,
  RotateCw,
  Hand,
  BarChart
} from "lucide-react";

export const metadata = {
  title: "Features - Divine Daily",
  description: "Explore the premium features of Divine Daily.",
};

const features = [
  { icon: ImageIcon, title: "Daily Devotional Images", desc: "Start your day with high-quality, beautiful images of your chosen deities." },
  { icon: MessageSquare, title: "AI Generated Captions", desc: "Each image is accompanied by a unique, spiritually uplifting caption generated by AI." },
  { icon: Heart, title: "Favorite Deities", desc: "Select which Gods and Goddesses you want to receive blessings from." },
  { icon: CheckCircle2, title: "Festival Greetings", desc: "Automatically receive special greetings and images on important Hindu festivals." },
  { icon: RotateCw, title: "Weekly Image Rotation", desc: "Never see the same image twice. Our system rotates through a vast library of divine artwork." },
  { icon: Clock, title: "Personalized Delivery Time", desc: "Set the exact time you want to receive your daily WhatsApp message." },
  { icon: Globe, title: "Language Selection", desc: "Get your captions and prayers in English, Hindi, or Sanskrit." },
  { icon: Hand, title: "Daily Prayer", desc: "Include a short, powerful daily prayer or mantra with your morning message." },
  { icon: MessageSquare, title: "WhatsApp Automation", desc: "Set it and forget it. Everything is delivered seamlessly via WhatsApp." },
  { icon: BarChart, title: "Analytics", desc: "Track how many messages you've received and view your daily inspiration streak." }
];

export default function FeaturesPage() {
  return (
    <div className="flex flex-col items-center py-24 bg-background min-h-screen">
      <div className="container px-4 md:px-6 mx-auto">
        <FadeIn className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold tracking-tighter mb-4 text-primary">Everything You Need for Daily Devotion</h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Our platform is designed to bring peace and spirituality into your daily routine, seamlessly delivered to your phone.
          </p>
        </FadeIn>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
          {features.map((feat, i) => (
            <FadeIn key={i} delay={i * 0.05}>
              <div className="flex flex-col p-8 bg-card rounded-3xl border border-border/50 shadow-sm hover:shadow-md transition-shadow h-full">
                <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center mb-6 text-primary">
                  <feat.icon className="w-7 h-7" />
                </div>
                <h3 className="text-2xl font-semibold mb-3">{feat.title}</h3>
                <p className="text-muted-foreground leading-relaxed flex-1">{feat.desc}</p>
              </div>
            </FadeIn>
          ))}
        </div>
      </div>
    </div>
  );
}
